create table campusinstitution
(
institution_id int2 primary key,
institution_name text,
institution_type text,
faculty text,
address jsonb,
location_co-ordinates geography,
opening_date date,
active_flag bool,
start_date date,
end_date date,
head_of_institution_name text,
institution_contact_detials jsonb,
email_id text,
date_established date,
accreditation_details text
iqac_establishment_date date,
aqar_year int,
cycle int2,
accreditation_year int,
grade text,
validity_period date,
institution_type text,
regultory_approval text,
program_categories text,
parent_institution text,
sequence_number int,
start_date date,
end_date date,
active_flag bool,
instution_status text,
campus_area text
number_of_classrooms int2,
number_of_labs int2,
seminar_conference_halls int2,
sports_facilities text,
library_details_book_journals_both_electronic_physical jsonb,
internet_availability text,
google_coordinates geography,
hostel_facility bool,
eligible_to_offer text,
entity text,
start_year text,
number_of_years_validity int2,
eligibility_status text,
inactive_from  date,
inactive_reason text
language text NOT NULL References language (code),
vision_statements jsonb,
university text NOT NULL References university(code),
education_group text NOT NULL References education_group(code),
institution_group text NOT NULL References institution_group(code),
);